name: Dependency Security Maintenance

on:
  schedule:
    - cron: "0 3 * * *" # every day at 03:00 UTC
  workflow_dispatch:

permissions: {}

jobs:
  npm-audit:
    uses: js-soft/github-actions/.github/workflows/dependency-security-maintenance.yml@main
    secrets:
      github-token: ${{ secrets.GH_PAT }}
